/** Feature-local copy so the panel can localize without editing dirty catalogs. */

import type { LocaleId } from "../../i18n/locale.js";

export const MANUAL_HISTORY_COPY = {
  "zh-CN": {
    disabled: "手动连续历史下载已关闭。",
    title: "手动连续历史",
    hint: "选择商品、周期和开始时间。系统会补到封口时最后一根已收盘 K 线。",
    protected: "成功数据并入用户数据集，并受 GC 保护。",
    startTime: "开始时间",
    startRequired: "必须填写开始时间。",
    endNotAllowed: "表单无效：不允许结束时间。",
    previewPlan: "预览计划",
    startDownload: "开始下载",
    cancel: "取消",
    exchange: "交易所",
    binance: "Binance",
    okx: "OKX",
    marketType: "市场类型",
    spot: "现货",
    futures: "永续合约",
    symbols: "商品（逗号分隔，可多选）",
    intervals: "周期（可多选）",
    customInterval: "自定义周期",
    addCustomInterval: "添加周期",
    customIntervalInvalid: "周期格式无效，例如 89m、2h 或 2M。",
    planSummary: "下载计划",
    effectiveStart: "有效起点",
    sealedEnd: "封存终点",
    planCanStart: "可以开始：{value}",
    estimatedStorage: "预计新增数据库字节：{value}",
    yes: "是",
    no: "否",
    unknown: "未知",
    recentJobs: "最近任务",
    protectedCollections: "受保护的数据集合",
    releaseProtection: "移除 GC 保护",
    released: "已移除保护",
    none: "暂无",
    polling: "正在同步任务状态…",
    partialNotComplete: "部分完成，不是一次完整下载。",
    blocked: "磁盘空间不足，任务已暂停。",
    failed: "下载失败。",
    succeeded: "下载已成功",
    jobState: "任务 {state}",
  },
  en: {
    disabled: "Manual history download is disabled.",
    title: "Manual continuous history",
    hint: "Select symbols, intervals, and a start time. The system fills to the last closed bar at seal time.",
    protected: "Successful data joins the user dataset and is GC-protected.",
    startTime: "Start time",
    startRequired: "Start time is required.",
    endNotAllowed: "Invalid form: end time is not allowed.",
    previewPlan: "Preview plan",
    startDownload: "Start download",
    cancel: "Cancel",
    exchange: "Exchange",
    binance: "Binance",
    okx: "OKX",
    marketType: "Market type",
    spot: "Spot",
    futures: "Perpetual futures",
    symbols: "Symbols (comma separated, multi-select)",
    intervals: "Intervals (multi-select)",
    customInterval: "Custom interval",
    addCustomInterval: "Add interval",
    customIntervalInvalid: "Invalid interval. Try 89m, 2h, or 2M.",
    planSummary: "Download plan",
    effectiveStart: "Effective start",
    sealedEnd: "Sealed end",
    planCanStart: "Can start: {value}",
    estimatedStorage: "Estimated database growth in bytes: {value}",
    yes: "Yes",
    no: "No",
    unknown: "Unknown",
    recentJobs: "Recent jobs",
    protectedCollections: "Protected data collections",
    releaseProtection: "Remove GC protection",
    released: "Protection removed",
    none: "None",
    polling: "Syncing job status…",
    partialNotComplete: "Partial is not a complete download.",
    blocked: "Disk is critical; the job is paused.",
    failed: "Download failed.",
    succeeded: "Download succeeded",
    jobState: "Job {state}",
  },
} as const;

export type ManualHistoryCopyKey = keyof typeof MANUAL_HISTORY_COPY.en;

export function manualHistoryText(
  locale: LocaleId,
  key: ManualHistoryCopyKey,
  vars?: Readonly<Record<string, string>>,
): string {
  const template = MANUAL_HISTORY_COPY[locale][key];
  if (!vars) return template;
  return template.replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (match, name: string) => {
    const value = vars[name];
    return value == null ? match : value;
  });
}
