export function buildChartWorkspaceViewModel({
  chartSettings,
  drawingActions,
  drawingView,
  exportActions,
  exportInProgress,
  exportView,
  indicatorComputing,
  indicatorView,
  marketActions,
  marketStatus,
  marketView,
  priceScaleActions,
  priceScaleView,
  resolvedTheme,
  sessionActions,
  sessionView,
  watchlistActions,
  watchlistView,
}) {
  const {
    symbol,
    exchange,
    marketType,
    interval,
    datasetKey,
    savedVisibleRange,
  } = sessionView;
  const chartStorageKeyBase = `${exchange}:${marketType}:${symbol}`;

  return {
    drawingToolbar: {
      activeTool: drawingView.drawingTool,
      onToolChange: drawingActions.setDrawingTool,
      penColor: drawingView.penColor,
      onPenColorChange: drawingActions.setPenColor,
      penSize: drawingView.penSize,
      onPenSizeChange: drawingActions.setPenSize,
      onClearAll: drawingActions.handleClearDrawing,
      drawingsHidden: drawingView.drawingsHidden,
      onToggleDrawingsHidden: drawingActions.handleToggleDrawingsHidden,
      drawingSnapEnabled: drawingView.drawingSnapEnabled,
      onDrawingSnapEnabledChange: drawingActions.handleDrawingSnapEnabledChange,
      textFontSize: drawingView.textFontSize,
      onTextFontSizeChange: drawingActions.setTextFontSize,
      textBold: drawingView.textBold,
      onTextBoldChange: drawingActions.setTextBold,
      textItalic: drawingView.textItalic,
      onTextItalicChange: drawingActions.setTextItalic,
      fibLevels: drawingView.fibLevels,
      onFibLevelsChange: drawingActions.handleFibLevelsChange,
      fibInverted: drawingView.fibInverted,
      onFibInvertedChange: drawingActions.handleFibInvertedChange,
      positionSize: drawingView.positionSize,
      onPositionSizeChange: drawingActions.handlePositionSizeChange,
      selectedDrawing: drawingView.selectedDrawing,
      onSelectedDrawingStyleChange: drawingActions.handleSelectedDrawingStyleChange,
      exportPanelOpen: exportView.isOpen,
      exportInProgress,
      onToggleExportPanel: exportActions.togglePanel,
    },
    exportPanel: {
      isOpen: exportView.isOpen,
      options: exportView.options,
      onOptionsChange: exportActions.updateOptions,
      onExport: exportActions.exportChart,
      onClose: exportActions.closePanel,
      inProgress: exportInProgress,
      error: exportView.error,
      notice: exportView.notice,
      metadata: exportView.metadata,
      loading: marketView.loading || marketStatus.loadingMoreLeft,
      indicatorComputing,
      preview: exportView.preview,
    },
    chart: {
      error: marketView.error,
      onRetryLoad: marketActions.retry,
      chartProps: {
        seriesStore: marketView.seriesStore,
        symbol,
        drawingKeyBase: chartStorageKeyBase,
        interval,
        loading: marketView.loading,
        onCrosshairMove: marketActions.onCrosshairMove,
        onNeedMoreLeft: marketActions.loadMoreLeft,
        canLoadMoreLeft: marketStatus.canLoadMoreLeft,
        datasetKey,
        upColor: chartSettings.upColor,
        downColor: chartSettings.downColor,
        theme: resolvedTheme,
        customBg: chartSettings.customBg,
        timezone: chartSettings.timezone,
        savedVisibleRange,
        dataMeta: marketView.meta,
        onVisibleRangeChange: marketActions.onVisibleRangeChange,
        drawingTool: drawingView.drawingTool,
        onDrawingToolChange: drawingActions.setDrawingTool,
        penColor: drawingView.penColor,
        penSize: drawingView.penSize,
        textFontSize: drawingView.textFontSize,
        textBold: drawingView.textBold,
        textItalic: drawingView.textItalic,
        fibLevels: drawingView.fibLevels,
        fibInverted: drawingView.fibInverted,
        positionSize: drawingView.positionSize,
        drawingSnapEnabled: drawingView.drawingSnapEnabled,
        onSelectedDrawingChange: drawingActions.handleSelectedDrawingChange,
        mainOverlayLines: indicatorView.mainOverlayLines,
        subPanes: indicatorView.subPanes,
        indicatorMarkers: indicatorView.markers,
        indicatorFills: indicatorView.fills,
        indicatorHlines: indicatorView.hlines,
        indicatorBgcolors: indicatorView.bgcolors,
        indicatorBarcolors: indicatorView.barcolors,
        invertScale: priceScaleView.invertScale,
        onInvertScaleChange: priceScaleActions.setInvertScale,
        priceScaleMode: priceScaleView.priceScaleMode,
        onPriceScaleModeChange: priceScaleActions.setPriceScaleMode,
      },
    },
    watchlist: {
      currentSymbol: symbol,
      currentMarketType: marketType,
      currentExchange: exchange,
      onSelectSymbol: sessionActions.selectSymbol,
      watchlists: watchlistView.watchlists,
      layout: watchlistView.layout,
      actions: watchlistActions,
      prices: watchlistView.prices,
      subscriptionTiers: watchlistView.subscriptionTiers,
      subscriptionResourceSummaries: watchlistView.subscriptionResourceSummaries,
      onTierChange: watchlistActions.handleTierChange,
      upColor: chartSettings.upColor,
      downColor: chartSettings.downColor,
    },
  };
}
