"""Public additive API for CandleScope Plugin Platform v2 authors."""

from .constants import (
    CONTROL_TRANSPORT_V1,
    DEFAULT_MAX_CONTAINER_ITEMS,
    DEFAULT_MAX_CONTROL_MESSAGE_BYTES,
    DEFAULT_MAX_IN_FLIGHT,
    DEFAULT_MAX_JSON_DEPTH,
    DEFAULT_MAX_STRING_BYTES,
    HOST_API_V1,
    JSONRPC_VERSION,
    MANIFEST_SCHEMA_VERSION,
    PLATFORM_SDK_API_VERSION,
    PLUGIN_PROTOCOL_V2,
)
from .errors import PlatformContractError, PlatformProtocolError
from .json_codec import (
    DEFAULT_JSON_LIMITS,
    JsonLimits,
    canonical_dumps,
    canonical_sha256,
    loads_strict,
    normalize_json,
)
from .models import (
    ActivationRequest,
    BackendEntrypoint,
    CapabilityGrant,
    Contribution,
    ContributionDescriptor,
    FrontendDefinition,
    FrontendSurface,
    HandshakeRequest,
    HostCallRequest,
    InvokeRequest,
    PermissionRequest,
    PermissionSet,
    PluginIdentity,
    PluginManifest,
    Probe,
    RequestContext,
    RuntimeDescriptor,
    descriptor_from_manifest,
)
from .rpc import (
    RpcError,
    RpcFailure,
    RpcFrame,
    RpcId,
    RpcRequest,
    RpcSuccess,
    parse_rpc_frame,
)
from .runtime import (
    BasePlatformPlugin,
    DeferredInvocation,
    HostCallInvocation,
    InvocationOutcome,
    PlatformDispatcher,
)
from .schema import manifest_schema
from .server import PlatformJsonLineServer, serve_platform_plugin


__all__ = [
    "ActivationRequest",
    "BackendEntrypoint",
    "BasePlatformPlugin",
    "CONTROL_TRANSPORT_V1",
    "CapabilityGrant",
    "Contribution",
    "ContributionDescriptor",
    "DEFAULT_JSON_LIMITS",
    "DEFAULT_MAX_CONTAINER_ITEMS",
    "DEFAULT_MAX_CONTROL_MESSAGE_BYTES",
    "DEFAULT_MAX_IN_FLIGHT",
    "DEFAULT_MAX_JSON_DEPTH",
    "DEFAULT_MAX_STRING_BYTES",
    "DeferredInvocation",
    "FrontendDefinition",
    "FrontendSurface",
    "HOST_API_V1",
    "HandshakeRequest",
    "HostCallInvocation",
    "HostCallRequest",
    "InvocationOutcome",
    "InvokeRequest",
    "JSONRPC_VERSION",
    "JsonLimits",
    "MANIFEST_SCHEMA_VERSION",
    "PLATFORM_SDK_API_VERSION",
    "PLUGIN_PROTOCOL_V2",
    "PermissionRequest",
    "PermissionSet",
    "PlatformContractError",
    "PlatformDispatcher",
    "PlatformJsonLineServer",
    "PlatformProtocolError",
    "PluginIdentity",
    "PluginManifest",
    "Probe",
    "RequestContext",
    "RpcError",
    "RpcFailure",
    "RpcFrame",
    "RpcId",
    "RpcRequest",
    "RpcSuccess",
    "RuntimeDescriptor",
    "canonical_dumps",
    "canonical_sha256",
    "descriptor_from_manifest",
    "loads_strict",
    "manifest_schema",
    "normalize_json",
    "parse_rpc_frame",
    "serve_platform_plugin",
]
